### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by iesmirnoff** [ilpwork/PetSide#1]
https://disk.yandex.ru/i/Sae5IEbSyqpS9w

1. Этого не должно быть
2. Тулбара в макете нет
3. Цвет статусбара не соответствует макету
4. Этой кнопки нет в макете

**Comment by ilpwork** [comment]
https://github.com/ilpwork/PetSide/commit/878f458ecadc3ccad22c0aa872a180476757160c
